=== Sai4158/411springBootJava/02-xml-testing/Testing_XML_LAB2/Patient.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://psu.edu/Patient"
    xmlns:tns="http://psu.edu/Patient"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified">

    <xsd:element name="patient" type="tns:Patient"/>

    <xsd:complexType name="Patient">
        <xsd:sequence>
            <xsd:element name="name" type="tns:String15Chars"/>
            <xsd:element name="age" type="xsd:int"/>
            <xsd:element name="dob" type="xsd:date"/>
            <xsd:element name="email" type="xsd:string" maxOccurs="unbounded"/>
            <xsd:element name="gender" type="tns:Gender"/>
            <xsd:element name="phone" type="xsd:string"/>
            <xsd:element name="payment" type="tns:PaymentType"/>
        </xsd:sequence>

        <xsd:attribute name="id" type="tns:ID" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="String15Chars">
        <xsd:restriction base="xsd:string">
            <xsd:maxLength value="15"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="Gender">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="M"/>
            <xsd:enumeration value="F"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="ID">
        <xsd:restriction base="xsd:int">
            <xsd:pattern value="[0-9]+"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="PaymentType">
        <xsd:choice>
            <xsd:element name="insurance" type="tns:Insurance"/>
            <xsd:element name="cash" type="xsd:int"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="Insurance">
        <xsd:all>
            <xsd:element name="providerName" type="xsd:string"/>
            <xsd:element name="limit" type="xsd:int"/>
        </xsd:all>
    </xsd:complexType>

</xsd:schema>

=== Sai4158/411springBootJava/02-xml-testing/Testing_XML/Patient.xml
<?xml version="1.0" encoding="UTF-8"?>

<tns:patient 
    xmlns:tns="http://psu.edu/Patient"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://psu.edu/Patient Patient.xsd" 
    id="123">

    <name>John</name>
    <age>40</age>
    <dob>1921-01-01</dob>
    <email>lomotey@psu.edu</email>
    <phone>7241234567</phone>
    
    <payment>
        <insurance>
            <providerName>Blue Cross</providerName>
            <limit>1000</limit>
        </insurance>
    </payment>
    
</tns:patient>

=== Sai4158/411springBootJava/02-xml-testing/Testing_XML_LAB2/Patient.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patient 
    xmlns:tns="http://psu.edu/Patient"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://psu.edu/Patient Patient.xsd" 
    id="123">

    <tns:name>John</tns:name>
    <tns:age>40</tns:age>
    <tns:dob>1921-01-01</tns:dob>
    <tns:email>lomotey.rich@psu.edu</tns:email>
    <tns:gender>M</tns:gender>
    <tns:phone>1234567890</tns:phone>

    <tns:payment>
        <tns:insurance>
            <tns:providerName>Blue Cross</tns:providerName>
            <tns:limit>1000</tns:limit>
        </tns:insurance>
    </tns:payment>
</tns:patient>
