=== Sai4158/411springBootJava/Assignment2/assignment2/textbooks.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://psu.edu/Textbooks"
            xmlns:tns="http://psu.edu/Textbooks"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified">

    <xsd:element name="textbooks">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="book" type="tns:BookType" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="BookType">
        <xsd:sequence>
            <xsd:element name="author" type="xsd:string"/>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="genre" type="tns:GenreType"/>
            <xsd:element name="price" type="xsd:decimal"/>
            <xsd:element name="publish_date" type="xsd:date"/>
            <xsd:element name="description" type="tns:DescriptionType"/>
        </xsd:sequence>
        <xsd:attribute name="bookID" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="GenreType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Computer"/>
            <xsd:enumeration value="Information Technology"/>
            <xsd:enumeration value="Management"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="DescriptionType">
        <xsd:sequence>
            <xsd:element name="summary">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:maxLength value="50"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="publisher" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== Sai4158/411springBootJava/02-xml-testing/Assignment2/assignment2/src/main/resources/textbooks.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:textbooks xmlns:tns="http://psu.edu/Textbooks"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://psu.edu/Textbooks textbooks.xsd">
    
    <tns:book bookID="bk101">
        <tns:author>Gambardella, Matthew</tns:author>
        <tns:title>XML Developer's Guide</tns:title>
        <tns:genre>Computer</tns:genre>
        <tns:price>44.95</tns:price>
        <tns:publish_date>2000-10-01</tns:publish_date>
        <tns:description>
            <tns:summary>An in-depth look at creating applications</tns:summary>
            <tns:publisher>Barnes &amp; Noble</tns:publisher>
        </tns:description>
    </tns:book>

    <tns:book bookID="bk102">
        <tns:author>Iwona Pisz, Sabina Kauf</tns:author>
        <tns:title>Industry 4.0</tns:title>
        <tns:genre>Information Technology</tns:genre>
        <tns:price>50.18</tns:price>
        <tns:publish_date>2021-11-01</tns:publish_date>
        <tns:description>
            <tns:summary>Challenges in Production Management</tns:summary>
            <tns:publisher>Routledge</tns:publisher>
        </tns:description>
    </tns:book>

</tns:textbooks>
